# Generated by Django 4.1.2 on 2022-12-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0011_rename_luutrufile_clipboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='lathuoc',
            name='hinhAnh',
            field=models.ImageField(default=None, upload_to='lathuoc'),
        ),
    ]
