# Generated by Django 4.1.2 on 2022-12-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0013_tintuc_hinhanh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintuc',
            name='hinhAnh',
            field=models.ImageField(default=None, upload_to='tintuc'),
        ),
    ]
