# Generated by Django 4.1.2 on 2022-12-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0015_cttintuc_hinhanh_alter_cttintuc_noidung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cttintuc',
            name='hinhAnh',
            field=models.ImageField(blank=True, default=False, upload_to='tintuc'),
        ),
        migrations.AlterField(
            model_name='cttintuc',
            name='noiDung',
            field=models.TextField(blank=True, default=''),
        ),
    ]
