# Generated by Django 4.1.2 on 2022-12-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0016_alter_cttintuc_hinhanh_alter_cttintuc_noidung'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donhang',
            old_name='maKhachHang',
            new_name='sdtKhachHang',
        ),
        migrations.AddField(
            model_name='donhang',
            name='diaChi',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='donhang',
            name='tenKhachHang',
            field=models.CharField(default='', max_length=255),
        ),
    ]
