# Generated by Django 4.1.2 on 2022-12-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0018_alter_donhang_diachi_alter_donhang_tenkhachhang'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='tongTien',
            field=models.IntegerField(default=0),
        ),
    ]
