# Generated by Django 4.1.2 on 2022-12-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0019_donhang_tongtien'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctdonhang',
            old_name='maDonHang',
            new_name='maCTDonHang',
        ),
        migrations.AddField(
            model_name='donhang',
            name='trangThai',
            field=models.IntegerField(default=0),
        ),
    ]
