# Generated by Django 4.1.2 on 2023-01-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0020_rename_madonhang_ctdonhang_mactdonhang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='khachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maKhachHang', models.CharField(max_length=255)),
                ('tenKhachHang', models.CharField(max_length=255)),
                ('ngaySinh', models.DateField(null=True)),
                ('diaChi', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='donhang',
            old_name='sdtKhachHang',
            new_name='maKhachHang',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='diaChi',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='tenKhachHang',
        ),
    ]
