# Generated by Django 4.1.2 on 2023-01-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0021_khachhang_rename_sdtkhachhang_donhang_makhachhang_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dieutri',
            old_name='maDieuTri',
            new_name='maLa',
        ),
    ]
