# Generated by Django 4.1.2 on 2023-01-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0026_alter_benhgan_chedosinhhoat_alter_benhgan_dieutri_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ctBenhGan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maCTBenhGan', models.CharField(max_length=255)),
                ('noiDung', models.TextField(blank=True, default='')),
                ('hinhAnh', models.ImageField(blank=True, default=False, upload_to='benhgan')),
                ('viTri', models.IntegerField()),
                ('kieuDuLieu', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ctLaThuoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maCTLa', models.CharField(max_length=255)),
                ('noiDung', models.TextField(blank=True, default='')),
                ('hinhAnh', models.ImageField(blank=True, default=False, upload_to='lathuoc')),
                ('viTri', models.IntegerField()),
                ('kieuDuLieu', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='cttintuc',
            old_name='maTinTuc',
            new_name='maCTTinTuc',
        ),
        migrations.RemoveField(
            model_name='benhgan',
            name='cheDoSinhHoat',
        ),
        migrations.RemoveField(
            model_name='benhgan',
            name='dieuTri',
        ),
        migrations.RemoveField(
            model_name='benhgan',
            name='nguyCo',
        ),
        migrations.RemoveField(
            model_name='benhgan',
            name='nguyenNhan',
        ),
        migrations.RemoveField(
            model_name='benhgan',
            name='timHieuChung',
        ),
        migrations.RemoveField(
            model_name='lathuoc',
            name='cachDung',
        ),
        migrations.RemoveField(
            model_name='lathuoc',
            name='hinhAnh',
        ),
        migrations.RemoveField(
            model_name='lathuoc',
            name='moTa',
        ),
        migrations.RemoveField(
            model_name='lathuoc',
            name='phanBo',
        ),
    ]
