# Generated by Django 4.1.2 on 2023-01-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0027_ctbenhgan_ctlathuoc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benhgan',
            name='hinhAnh',
            field=models.ImageField(default=None, upload_to='benhgan'),
        ),
        migrations.AddField(
            model_name='lathuoc',
            name='hinhAnh',
            field=models.ImageField(default=None, upload_to='lathuoc'),
        ),
    ]
