# Generated by Django 4.1.2 on 2023-01-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0028_benhgan_hinhanh_lathuoc_hinhanh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lathuoc',
            name='maLa',
        ),
    ]
