# Generated by Django 4.1.2 on 2023-01-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0031_alter_lathuoc_mala'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ctLaThuoc',
        ),
        migrations.DeleteModel(
            name='ctTinTuc',
        ),
        migrations.AddField(
            model_name='lathuoc',
            name='noiDungKhac',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tintuc',
            name='noiDungKhac',
            field=models.TextField(blank=True, null=True),
        ),
    ]
