# Generated by Django 4.1.2 on 2023-01-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0032_delete_ctlathuoc_delete_cttintuc_lathuoc_noidungkhac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadId', models.CharField(max_length=255)),
                ('uploadContent', models.CharField(max_length=255)),
                ('hinhAnh', models.FileField(upload_to='uploads')),
            ],
        ),
        migrations.AlterField(
            model_name='lathuoc',
            name='hinhAnh',
            field=models.ImageField(default=None, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='tintuc',
            name='hinhAnh',
            field=models.ImageField(default=None, upload_to='uploads'),
        ),
    ]
