# Generated by Django 4.1.2 on 2023-01-11 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0033_upload_alter_lathuoc_hinhanh_alter_tintuc_hinhanh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='hinhAnh',
            new_name='file',
        ),
    ]
