# Generated by Django 4.1.2 on 2023-01-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0034_rename_hinhanh_upload_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ctBenhGan',
        ),
        migrations.AddField(
            model_name='benhgan',
            name='noiDungKhac',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benhgan',
            name='hinhAnh',
            field=models.ImageField(default=None, upload_to='uploads'),
        ),
    ]
