# Generated by Django 4.1.2 on 2023-01-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0035_delete_ctbenhgan_benhgan_noidungkhac_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khachhang',
            old_name='maKhachHang',
            new_name='soDienThoai',
        ),
    ]
