# Generated by Django 4.1.2 on 2023-01-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0036_rename_makhachhang_khachhang_sodienthoai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintuc',
            name='ngayDang',
            field=models.DateField(),
        ),
    ]
