# Generated by Django 4.1.2 on 2023-01-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0038_remove_khachhang_ngaysinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='ghiChu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
