# Generated by Django 4.1.2 on 2023-02-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0039_khachhang_ghichu'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('image', models.ImageField(default=None, upload_to='data_train')),
            ],
        ),
    ]
